// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQbIBtP6U7wXlfcgKqkQKbMBlcQD1v9bQ',
    appId: '1:998850827592:web:a116daf07cc59ca1698f7d',
    messagingSenderId: '998850827592',
    projectId: 'e-commerce-app-a577d',
    authDomain: 'e-commerce-app-a577d.firebaseapp.com',
    storageBucket: 'e-commerce-app-a577d.appspot.com',
    measurementId: 'G-54C2KZWB61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9202JBCgYSNHXjm_nuWTElO-6TgZRSks',
    appId: '1:998850827592:android:971f551373a109d8698f7d',
    messagingSenderId: '998850827592',
    projectId: 'e-commerce-app-a577d',
    storageBucket: 'e-commerce-app-a577d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcjR-z8hzluLxpSxy-4eqE48VNbZLDyI4',
    appId: '1:998850827592:ios:b484f8f4fc120a3b698f7d',
    messagingSenderId: '998850827592',
    projectId: 'e-commerce-app-a577d',
    storageBucket: 'e-commerce-app-a577d.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcjR-z8hzluLxpSxy-4eqE48VNbZLDyI4',
    appId: '1:998850827592:ios:b484f8f4fc120a3b698f7d',
    messagingSenderId: '998850827592',
    projectId: 'e-commerce-app-a577d',
    storageBucket: 'e-commerce-app-a577d.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQbIBtP6U7wXlfcgKqkQKbMBlcQD1v9bQ',
    appId: '1:998850827592:web:823b1e7a26ded0db698f7d',
    messagingSenderId: '998850827592',
    projectId: 'e-commerce-app-a577d',
    authDomain: 'e-commerce-app-a577d.firebaseapp.com',
    storageBucket: 'e-commerce-app-a577d.appspot.com',
    measurementId: 'G-4YGH3G8LFX',
  );
}
